service: goes-notify-bot

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-1

functions:
  bot:
    handler: src/bot.botHandler
    events:
      - http:
          path: bot
          method: post
  check:
    handler: src/check.checkAppointments
    events:
      - schedule: rate(15 minutes)

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: 'node14'